use_frameworks!

platform :ios, '10.0'

target 'MyCocoapodLibrary_Example' do
  pod 'MyCocoapodLibrary', :path => '../'

  target 'MyCocoapodLibrary_Tests' do
    inherit! :search_paths

    
  end
end
